version: '3.9'

services:
  app:
    # Use your pre-built image name here
    image: testing_sec_pass_app:latest
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PYTHONUNBUFFERED=1
      # Move non-sensitive items here from your .env
      - CONFIG_BASE_URL=https://portal.simplyhosting.com/admin/devicemanagement/device/info/id/
      - INFO_SELECTOR=#server-tab
      - AUDIT_SELECTOR=#audit-tab
    secrets:
      - WHMCS_API_URL
      - WHMCS_API_IDENTIFIER
      - WHMCS_API_SECRET
      - LOGIN_URL
      - PORTAL_USER
      - PORTAL_PASS
    command: gunicorn --workers 2 --threads 4 --timeout 120 --bind 0.0.0.0:8000 app:app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # Note: In Swarm, the path must be absolute or exist on the host
      - /home/lnikuskina/testing_sec_pass/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: any

# This section tells Swarm to use the secrets you created via CLI
secrets:
  WHMCS_API_URL:
    external: true
  WHMCS_API_IDENTIFIER:
    external: true
  WHMCS_API_SECRET:
    external: true
  LOGIN_URL:
    external: true
  PORTAL_USER:
    external: true
  PORTAL_PASS:
    external: true
